package dev.uten2c.fluoritedatagenerator;

import net.minecraft.sound.BlockSoundGroup;

@SuppressWarnings("SpellCheckingInspection")
public enum BlockSoundGroupType {
    WOOD(BlockSoundGroup.WOOD),
    GRAVEL(BlockSoundGroup.GRAVEL),
    GRASS(BlockSoundGroup.GRASS),
    LILY_PAD(BlockSoundGroup.LILY_PAD),
    STONE(BlockSoundGroup.STONE),
    METAL(BlockSoundGroup.METAL),
    GLASS(BlockSoundGroup.GLASS),
    WOOL(BlockSoundGroup.WOOL),
    SAND(BlockSoundGroup.SAND),
    SNOW(BlockSoundGroup.SNOW),
    POWDER_SNOW(BlockSoundGroup.POWDER_SNOW),
    LADDER(BlockSoundGroup.LADDER),
    ANVIL(BlockSoundGroup.ANVIL),
    SLIME(BlockSoundGroup.SLIME),
    HONEY(BlockSoundGroup.HONEY),
    WET_GRASS(BlockSoundGroup.WET_GRASS),
    CORAL(BlockSoundGroup.CORAL),
    BAMBOO(BlockSoundGroup.BAMBOO),
    BAMBOO_SAPLING(BlockSoundGroup.BAMBOO_SAPLING),
    SCAFFOLDING(BlockSoundGroup.SCAFFOLDING),
    SWEET_BERRY_BUSH(BlockSoundGroup.SWEET_BERRY_BUSH),
    CROP(BlockSoundGroup.CROP),
    STEM(BlockSoundGroup.STEM),
    VINE(BlockSoundGroup.VINE),
    NETHER_WART(BlockSoundGroup.NETHER_WART),
    LANTERN(BlockSoundGroup.LANTERN),
    NETHER_STEM(BlockSoundGroup.NETHER_STEM),
    NYLIUM(BlockSoundGroup.NYLIUM),
    FUNGUS(BlockSoundGroup.FUNGUS),
    ROOTS(BlockSoundGroup.ROOTS),
    SHROOMLIGHT(BlockSoundGroup.SHROOMLIGHT),
    WEEPING_VINES(BlockSoundGroup.WEEPING_VINES),
    WEEPING_VINES_LOW_PITCH(BlockSoundGroup.WEEPING_VINES_LOW_PITCH),
    SOUL_SAND(BlockSoundGroup.SOUL_SAND),
    SOUL_SOIL(BlockSoundGroup.SOUL_SOIL),
    BASALT(BlockSoundGroup.BASALT),
    WART_BLOCK(BlockSoundGroup.WART_BLOCK),
    NETHERRACK(BlockSoundGroup.NETHERRACK),
    NETHER_BRICKS(BlockSoundGroup.NETHER_BRICKS),
    NETHER_SPROUTS(BlockSoundGroup.NETHER_SPROUTS),
    NETHER_ORE(BlockSoundGroup.NETHER_ORE),
    BONE(BlockSoundGroup.BONE),
    NETHERITE(BlockSoundGroup.NETHERITE),
    ANCIENT_DEBRIS(BlockSoundGroup.ANCIENT_DEBRIS),
    LODESTONE(BlockSoundGroup.LODESTONE),
    CHAIN(BlockSoundGroup.CHAIN),
    NETHER_GOLD_ORE(BlockSoundGroup.NETHER_GOLD_ORE),
    GILDED_BLACKSTONE(BlockSoundGroup.GILDED_BLACKSTONE),
    CANDLE(BlockSoundGroup.CANDLE),
    AMETHYST_BLOCK(BlockSoundGroup.AMETHYST_BLOCK),
    AMETHYST_CLUSTER(BlockSoundGroup.AMETHYST_CLUSTER),
    SMALL_AMETHYST_BUD(BlockSoundGroup.SMALL_AMETHYST_BUD),
    MEDIUM_AMETHYST_BUD(BlockSoundGroup.MEDIUM_AMETHYST_BUD),
    LARGE_AMETHYST_BUD(BlockSoundGroup.LARGE_AMETHYST_BUD),
    TUFF(BlockSoundGroup.TUFF),
    CALCITE(BlockSoundGroup.CALCITE),
    DRIPSTONE_BLOCK(BlockSoundGroup.DRIPSTONE_BLOCK),
    POINTED_DRIPSTONE(BlockSoundGroup.POINTED_DRIPSTONE),
    COPPER(BlockSoundGroup.COPPER),
    CAVE_VINES(BlockSoundGroup.CAVE_VINES),
    SPORE_BLOSSOM(BlockSoundGroup.SPORE_BLOSSOM),
    AZALEA(BlockSoundGroup.AZALEA),
    FLOWERING_AZALEA(BlockSoundGroup.FLOWERING_AZALEA),
    MOSS_CARPET(BlockSoundGroup.MOSS_CARPET),
    MOSS_BLOCK(BlockSoundGroup.MOSS_BLOCK),
    BIG_DRIPLEAF(BlockSoundGroup.BIG_DRIPLEAF),
    SMALL_DRIPLEAF(BlockSoundGroup.SMALL_DRIPLEAF),
    ROOTED_DIRT(BlockSoundGroup.ROOTED_DIRT),
    HANGING_ROOTS(BlockSoundGroup.HANGING_ROOTS),
    AZALEA_LEAVES(BlockSoundGroup.AZALEA_LEAVES),
    SCULK_SENSOR(BlockSoundGroup.SCULK_SENSOR),
    SCULK_CATALYST(BlockSoundGroup.SCULK_CATALYST),
    SCULK(BlockSoundGroup.SCULK),
    SCULK_VEIN(BlockSoundGroup.SCULK_VEIN),
    SCULK_SHRIEKER(BlockSoundGroup.SCULK_SHRIEKER),
    GLOW_LICHEN(BlockSoundGroup.GLOW_LICHEN),
    DEEPSLATE(BlockSoundGroup.DEEPSLATE),
    DEEPSLATE_BRICKS(BlockSoundGroup.DEEPSLATE_BRICKS),
    DEEPSLATE_TILES(BlockSoundGroup.DEEPSLATE_TILES),
    POLISHED_DEEPSLATE(BlockSoundGroup.POLISHED_DEEPSLATE),
    FROGLIGHT(BlockSoundGroup.FROGLIGHT),
    FROGSPAWN(BlockSoundGroup.FROGSPAWN),
    MANGROVE_ROOTS(BlockSoundGroup.MANGROVE_ROOTS),
    MUDDY_MANGROVE_ROOTS(BlockSoundGroup.MUDDY_MANGROVE_ROOTS),
    MUD(BlockSoundGroup.MUD),
    MUD_BRICKS(BlockSoundGroup.MUD_BRICKS),
    PACKED_MUD(BlockSoundGroup.PACKED_MUD),
    HANGING_SIGN(BlockSoundGroup.HANGING_SIGN),
    NETHER_WOOD_HANGING_SIGN(BlockSoundGroup.NETHER_WOOD_HANGING_SIGN),
    BAMBOO_WOOD_HANGING_SIGN(BlockSoundGroup.BAMBOO_WOOD_HANGING_SIGN),
    BAMBOO_WOOD(BlockSoundGroup.BAMBOO_WOOD),
    NETHER_WOOD(BlockSoundGroup.NETHER_WOOD),
    CHISELED_BOOKSHELF(BlockSoundGroup.CHISELED_BOOKSHELF),
    ;

    private final BlockSoundGroup group;

    BlockSoundGroupType(BlockSoundGroup group) {
        this.group = group;
    }

    public BlockSoundGroup getGroup() {
        return group;
    }
}
